### ISSUE TITLE
Does not set default search engine for Chrome

### ISSUE THREAD

**Issue by sirianni** [kagisearch/browser_extensions#32] opened 2023-09-25 13:50 UTC
Installing the Chrome extension only provides the "Summarization" feature and does not actually set the default search engine.

**Comment by gauntface** [comment] 2023-09-25 22:57
yeah I just noticed this as well.

I could have sworn it worked when I first installed it, but I may be imagining it.

**Comment by BrunoBernardino** [comment] 2023-09-26 09:36
Thanks for reporting this, guys! This doesn't work at all with Chrome. See https://github.com/kagisearch/browser_extensions/issues/2 which this is a duplicate of.

**Closed by BrunoBernardino** 2023-09-26 09:36 UTC

**Comment by sirianni** [comment] 2023-09-27 01:04
Is there a way to get the auto-suggest to work with Chrome when setting up `Site Search` manually?

**Comment by vprelovac** [comment] 2023-09-27 02:37
If it allows you specify autosuggest url, here is the specification:

https://help.kagi.com/kagi/getting-started/setting-default.html#custom_use

**Comment by sirianni** [comment] 2023-09-29 13:20
> If it allows 
It doesn't allow you to.

![image](https://github.com/kagisearch/browser_extensions/assets/381302/419a8a61-24f5-4614-9859-72d84ad75fde)

I'm aware of the specification, yes.

**Comment by sirianni** [comment] 2023-09-29 13:22
BTW, thanks for the response and fantastic work on Kagi!  :slightly_smiling_face:
