### ISSUE TITLE
Kagi extension loses auth in private browser window

### ISSUE THREAD

**Issue by a1russell** [kagisearch/browser_extensions#28] opened 2023-09-12 20:37 UTC
Every time I restart my browser, my Kagi extension loses its authentication for private windows. In case it matters, I am using the Brave browser.

To outline the issue in steps:

1. Start browser with the Kagi extension installed
2. Open a New Private Window
3. Type a query in the URL bar and hit Enter
4. Instead of seeing search results as expected, get redirected to https://kagi.com/signin

A workaround is to go into the extension settings and disable and then re-enable the Kagi extension, but it's a pain to do this every time.

**Comment by vprelovac** [comment] 2023-09-12 22:57
@a1russell Can you try to reproduce this in Chrome, to see if this is a Brave specific behavior?

**Comment by a1russell** [comment] 2023-09-13 13:23
I just installed the extension in Chrome (which I haven't used in quite a long time, trying to limit my usage of Google products), and after enabling "Allow in Incognito" on the extension, it did not exhibit the same issue. It worked as I would expect.

**Comment by vprelovac** [comment] 2023-09-13 17:00
OK so it seems to be a Brave related issue, which limits what we can do about it. Not sure if they introduced something recently.

**Comment by vprelovac** [comment] 2023-09-13 17:57
@BrunoBernardino is this something you can prioritize, at least understanding if it is fixable or is it a limitation with Brave

**Comment by BrunoBernardino** [comment] 2023-09-15 08:29
Thanks for reporting this @a1russell ! The Kagi Search extension doesn't set the default search engine in Chromium browsers (see #2), so this is a setting you need to change in `brave://settings/search` (the token is probably outdated there, in the URL -- should be `https://kagi.com/search?token=TOKEN&q=%s` with the token piece you can see in [your settings](https://kagi.com/settings?p=user_details)). When you reactivate the extension you're just having it update the token that then sends to `kagi.com` but the initial setting in your Brave browser's search settings is what it gets started with and what should be updated.

Unfortunately, as #2 is tracking, this is a limitation with Chromium-based browsers, which don't allow extensions to set default search engines.

@vprelovac it seems we might be missing an indicator/note for the private session search for Chrome-based browsers like we have for Firefox in https://help.kagi.com/kagi/getting-started/setting-default.html#firefox_desktop

I'm closing as it's effectively something to be tracked/fixed by #2 if/whenever Google enables that.

**Closed by BrunoBernardino** 2023-09-15 08:29 UTC
